### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by alecumitu** [rbtl-fs24/md-03-assignments-alecumitu#1]
@larnsce

**Comment by larnsce** [comment]
Thank you for working through the assignment, @alecumitu. 

Did you also work on: [md-03b-sanitation-visualise.qmd](https://github.com/rbtl-fs24/md-03-assignments-alecumitu/blob/main/md-03b-sanitation-visualise.qmd)? I can only see a commit with code for md-03a

**Comment by alecumitu** [comment]
@larnsce sorry, forgot to commit. Now it's done. Thank you!
